#%RAML 1.0
title: New API
'/login/{ath}':
  post:
    responses:
      '200':
        description: Details are correct
        body:
          application/json:
            example: Successfully Logged in
            default: Successfully Logged in
            type: string
      '400':
        description: Bad Request
      '401':
        description: Details are inccorect
    body:
      application/json:
        type: object
        properties:
          userName:
            required: true
            example: monica
            description: Property description
            type: string
          emailId:
            required: true
            pattern: '[A-Za-z0-9]{6,18}[@][a-z]{4,10}[.][a-z ]{2,5}'
            example: monicadabas34@gmail.com
            description: Property description
            type: string
          password:
            required: true
            pattern: '[a-zA-Z0-9@$#]{6,18}'
            example: monica@17
            description: Property description
            type: string
  uriParameters:
    ath:
      example: Example
      description: Property description
      type: string
